
# PfamDB.pm
# jt6 20060808 WTSI
#
# $Id: PfamDB.pm,v 1.9 2007-09-07 16:05:30 jt6 Exp $

=head1 NAME

PfamWeb::Model::PfamDB - a wrapper around the pfam database schema

=cut

package PfamWeb::Model::PfamDB;

=head1 DESCRIPTION

The model for the database is defined in a L<DBIx::Class::Schema>,
C<PfamDB>. This is a wrapper around that schema, which imports
auto-generates the L<Catalyst::Model> classes at runtime, using the
schema classes to define the components.

As the base class for the database model, this class also instantiates
a L<Bio::Das::Lite> object, which can be retrieved by controllers using
C<getDasLite>, something like

=over

=item C<$c->model("PfamDB")->getDasLite>

=back

The object is instantiated if it has not been generated by a previous
call on this method. The configuration parameters are stored in the
top level configuration file.

$Id: PfamDB.pm,v 1.9 2007-09-07 16:05:30 jt6 Exp $

=cut

use strict;
use warnings;

use base qw/Catalyst::Model::DBIC::Schema/;

use Bio::Das::Lite;

#-------------------------------------------------------------------------------

=head1 METHODS

=head2 getDasLite

Returns the L<Bio::Das::Lite> object, instantiating it first if necessary.

=cut

sub getDasLite {
  my( $this ) = @_;

  if( not defined $this->{dasLiteObj} ) {
    my( $dsn, $to, $proxy );
    ( $dsn   ) = $this->{dasDsn}         =~ /^([\w\:\/\-\?\#]+)$/;
    ( $to    ) = $this->{dasTo}          =~ /^(\d+)$/;
    ( $proxy ) = $this->{dasProxy} || '' =~ /^([\w\:\/\.\-\?\#]+)$/;

    my %options = ( dsn     => $dsn,
                    timeout => $to );
    $options{http_proxy} = $proxy if defined $proxy;

    $this->{dasLiteObj} = Bio::Das::Lite->new( \%options );
  }

  return $this->{dasLiteObj};
}

#-------------------------------------------------------------------------------

=head1 AUTHOR

John Tate, C<jt6@sanger.ac.uk>

Rob Finn, C<rdf@sanger.ac.uk>

=head1 COPYRIGHT

Copyright (c) 2007: Genome Research Ltd.

Authors: Rob Finn (rdf@sanger.ac.uk), John Tate (jt6@sanger.ac.uk)

This is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
or see the on-line version at http://www.gnu.org/copyleft/gpl.txt

=cut

1;
